// Site Configuration — Generated by Polaris Point Admin
// Template: plumber | Theme: Professional
window.SITE_CONFIG = {

  // === THEME (Professional — Navy & Orange) ===
  theme: {
    primary: "#1B3A6B",
    primaryDark: "#0f2748",
    accent: "#E8601E",
    accentLight: "#FF7A3D",
    bg: "#f6f8fc",
    text: "#173052",
    muted: "rgba(23,48,82,.55)",
    fontHeading: "'Montserrat', sans-serif",
    fontBody: "'Source Sans 3', sans-serif",
    logoUrl: "data:image/svg+xml;utf8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20320%2080%22%20width%3D%22320%22%20height%3D%2280%22%3E%3Crect%20width%3D%22320%22%20height%3D%2280%22%20fill%3D%22transparent%22%2F%3E%3Ctext%20x%3D%22160%22%20y%3D%2250%22%20text-anchor%3D%22middle%22%20font-family%3D%22Outfit%2C%20sans-serif%22%20font-weight%3D%22700%22%20font-size%3D%2228%22%20fill%3D%22%23D4A853%22%20letter-spacing%3D%22-.5%22%3EHaddad%20Plumbing%3C%2Ftext%3E%3Cline%20x1%3D%2280%22%20y1%3D%2262%22%20x2%3D%22240%22%20y2%3D%2262%22%20stroke%3D%22%23D4A853%22%20stroke-width%3D%221.5%22%20opacity%3D%22.5%22%2F%3E%3C%2Fsvg%3E"
  },

  // === PAGE META ===
  pageTitle: "Haddad Plumbing & Heating Inc | NJ 07114",
  metaDescription: "Haddad Plumbing & Heating Inc offers fast, reliable service. Licensed and insured.",

  // === IDENTITY ===
  businessName: "Haddad Plumbing & Heating Inc",
  businessNameShort: "Haddad Plumbing",
  licenseNumber: "",

  // === CONTACT ===
  phone: "(973) 424-1177",
  phoneTelHref: "tel:+19734241177",
  email: "info@example.com",
  emailHref: "mailto:info@example.com",
  address: "1223 Broad St, Newark, NJ 07114, USA",
  hours: "Monday: 8:00 AM – 6:00 PM | Tuesday: 8:00 AM – 6:00 PM | Wednesday: 8:00 AM – 6:00 PM | Thursday: 8:00 AM – 6:00 PM | Friday: 8:00 AM – 6:00 PM | Saturday: 8:00 AM – 6:00 PM | Sunday: Closed",

  // === TOPBAR ===
  topbarText: "24/7 Emergency Service Available",

  // === HERO ===
  heroHeadline: "Haddad Plumbing & Heating Inc",
  heroSubtext: "Licensed & insured plumber proudly serving NJ 07114 and surrounding areas. Rated 3.3 stars by 75+ customers. Call today for a free estimate.",
  heroImage: "https://images.pexels.com/photos/6419128/pexels-photo-6419128.jpeg?auto=compress&cs=tinysrgb&w=800",
  heroImageAlt: "Haddad Plumbing & Heating Inc - professional service",
  heroCta1: "Call (973) 424-1177",
  heroCta2: "Get a Free Estimate",

  // === TRUST BADGES ===
  trustBadge1: "Licensed & Insured",
  trustBadge2: "5-Star Rated",
  trustBadge3: "Locally Owned",
  trustBadge4: "10+ Years Experience",

  // === SERVICES ===
  servicesLabel: "What We Do",
  servicesTitle: "Our Services",
  service1Name: "Drain Cleaning",
  service1Desc: "Clogged drains fixed quickly with professional-grade hydro-jetting and cable equipment.",
  service2Name: "Water Heater Repair",
  service2Desc: "Repair or upgrade your tank or tankless water heater for reliable hot water every day.",
  service3Name: "Leak Detection",
  service3Desc: "Find hidden leaks fast with electronic detection equipment and prevent expensive damage.",
  service4Name: "Fixture Repair",
  service4Desc: "Stop constant drips and running toilets with lasting faucet, toilet, and fixture repairs.",
  service5Name: "Pipe Installation",
  service5Desc: "New pipe installs and whole-house re-pipes built for code compliance and long-term flow.",

  // === ABOUT ===
  aboutImage: "https://images.pexels.com/photos/8961699/pexels-photo-8961699.jpeg?auto=compress&cs=tinysrgb&w=800",
  aboutImageAlt: "Haddad Plumbing & Heating Inc team",
  aboutLabel: "Why Choose Us",
  aboutTitle: "NJ 07114 Trusts Haddad Plumbing",
  aboutText: "Haddad Plumbing & Heating Inc has been serving NJ 07114 with reliable, professional plumber services. With a 3.3-star rating from 75 customers, we take pride in quality work and honest pricing. Every job is treated with care and respect.",

  // === WHY CARDS ===
  why1Title: "Same-Day Service",
  why1Text: "Most calls handled the same day.",
  why2Title: "Upfront Pricing",
  why2Text: "Clear quotes before work starts. No surprise fees.",
  why3Title: "Satisfaction Guaranteed",
  why3Text: "If the problem comes back, so do we.",

  // === REVIEWS ===
  reviewsLabel: "Testimonials",
  reviewsTitle: "What Our Customers Say",
  reviews: [
    {
      text: "Haddad plumbing has saved us numerous times. They are professional, reliable and consistent. We had a few repairs and a few total replacements and I would pick them every time for future work.",
      attribution: "Jaime G &middot; 10 months ago",
      rating: 5
    }
  ],

  // === SERVICE AREA ===
  serviceAreaLabel: "Coverage Area",
  serviceAreaTitle: "Serving NJ 07114 & Surrounding Areas",
  serviceAreaText: "",
  serviceAreaImage: "/api/photo?ref=AaVGc3n1s1atLRZZQpBWKzJibW5LkCYfXCPKSjvEUVgsUV912ihX0vs1nMANh4_gmF7bBmQX5VQrPVpjH5LWiORyFR2HEuGOcZMGgjeoVj8zx8zo_b6oUEiOkYSvApAXsZKYu-UB5xrx1xuf-3ukGS-Je9GCupVpEYwNUcLgB67LOzBTbf40NhhGOJvoXSBCxCEC6Tc08IqLBl-3sBaXkQosoamXmkW0gDIp-EMmKW4iUky9Fp5BdPcL50cA9-Fpp1vd9yYqrrvcvtpk7fwtFFua3nz3MOHgFYx8bTLgsMANCTeDbN0vt9ARuzuOIKeak66jJmhzrKharHcmhPrkc9_BTr3Ysoyq2I5f0TFmRPB_nx2XpVitwRD06ogOZvLWxSsbdDkkWfcjv15HcnRwM1S0c-mORqKuUKK4IsN0XP1WV7sAog&maxwidth=800",
  serviceAreaImageAlt: "Serving NJ 07114",
  serviceAreas: ["NJ 07114"],

  // === CONTACT FORM ===
  contactLabel: "Get In Touch",
  contactTitle: "Request Your Free Estimate",
  contactText: "Fill out the form and we will get back to you within 2 hours during business hours.",
  formServiceOptions: ["Drain Cleaning","Water Heater Repair","Leak Detection","Fixture Repair","Pipe Installation","Other"],

  // === CTA BANNER ===
  ctaTitle: "Need Help Right Now?",
  ctaText: "Our team is available to help you today.",
  ctaButton: "Call (973) 424-1177",

  // === FOOTER ===
  footerDescription: "Haddad Plumbing & Heating Inc. Licensed, insured, and committed to getting the job done right.",
  footerLegal: "&copy; 2026 Haddad Plumbing & Heating Inc. All rights reserved. &middot; <a href=\"/privacy\">Privacy</a> &middot; <a href=\"/terms\">Terms</a> &middot; <a href=\"/accessibility\">Accessibility</a>",
  footerServices: ["Drain Cleaning","Water Heater Repair","Leak Detection","Fixture Repair","Pipe Installation"],

  // === FEATURE FLAGS ===
  features: {
    mobileNav: true,
    activeNavHighlight: true,
    stickyHeader: true,
    smoothScroll: true,
    formHandling: true,
    scrollReveal: true,
    reviewCarousel: true,
    googleReviewsBadge: true,
    floatingButtons: true,
    stickyBottomCta: true,
    exitIntent: true,
    urgencyBanner: true,
    faqAccordion: true,
    serviceAreaMap: true,
    lightbox: true,
    teamModals: false,
    blogPreview: true,
    cookieConsent: true,
    trustBar: true,
    analytics: false
  },

  // === GOOGLE REVIEWS ===
  googleReviewsRating: "3.3",
  googleReviewsCount: "75",
  googleReviewsUrl: "https://maps.google.com/?cid=16161932002676851665",

  // === ENGAGEMENT ===
  smsNumber: "9734241177",
  whatsappNumber: "",
  calcomUrl: "",

  exitIntent: {
    headline: "Wait — Get $50 Off Your First Service",
    text: "Book your service today and save. New customers only.",
    cta: "Claim My Discount",
    ctaUrl: "#contact"
  },

  urgencyBanner: {
    text: "Limited Time Offer — Call today for a free estimate",
    endDate: "2026-12-31"
  },

  // === FAQ ===
  faqs: [
    { question: "Do you offer free estimates?", answer: "Yes! We provide free, no-obligation estimates for all plumbing work. Call us or fill out our online form and we'll get back to you the same day." },
    { question: "Are your plumbers licensed and insured?", answer: "Absolutely. Every technician on our team is fully licensed, bonded, and insured for your protection and peace of mind." },
    { question: "Do you offer emergency plumbing services?", answer: "Yes, we offer 24/7 emergency plumbing services. Burst pipes, major leaks, and sewer backups can't wait — and neither do we." },
    { question: "How quickly can you get to my home?", answer: "For most service calls, we can have a technician at your door within 1-2 hours. Emergency calls are prioritized for fastest response." },
    { question: "What types of plumbing services do you offer?", answer: "We handle everything from simple repairs and drain cleaning to water heater installation, repiping, sewer line work, and full bathroom/kitchen remodels." },
    { question: "Do you guarantee your work?", answer: "Yes. All of our work comes with a satisfaction guarantee. If something isn't right, we'll come back and fix it at no additional charge." }
  ],

  // === SERVICE AREA MAP ===
  googleMapsEmbed: "https://www.google.com/maps?q=1223%20Broad%20St%2C%20Newark%2C%20NJ%2007114%2C%20USA&output=embed",

  // === BLOG POSTS ===
  blogPosts: [
    { title: "5 Signs You Need to Replace Your Water Heater — {short} Explains", excerpt: "Is your water heater making strange noises, producing rusty water, or taking forever to heat up? The team at Haddad Plumbing & Heating Inc breaks down the warning signs that replacement may be cheaper than another repair.", image: "", url: "#", date: "2026-06-06" },
    { title: "How NJ 07114 Homeowners Can Prevent Frozen Pipes This Winter", excerpt: "Frozen pipes can burst and cause thousands in water damage. Haddad Plumbing & Heating Inc shares the simple steps — insulating exposed pipes, keeping faucets dripping, and knowing where your main shutoff is — that save NJ 07114 homeowners from disaster.", image: "", url: "#", date: "2026-06-06" },
    { title: "Why Your Drains Keep Clogging — Tips from {short}", excerpt: "Recurring clogs aren't just annoying — they're a sign of a bigger problem. Haddad Plumbing & Heating Inc explains what's really going on in your pipes, from grease buildup to tree root intrusion, and when to call a professional.", image: "", url: "#", date: "2026-06-06" }
  ],

  team: [
  ],

  // === TRUST BAR LOGOS ===
  trustLogos: [
    { src: "", alt: "Licensed & Insured" },
    { src: "", alt: "BBB A+ Rated" },
    { src: "", alt: "Google Guaranteed" }
  ],

  // === SEO ===
  canonicalUrl: "",
  ogImage: "",
  geoRegion: "",
  geoPlacename: "NJ 07114",
  geoPosition: "",
  schema: {
    type: "LocalBusiness",
    additionalType: "",
    priceRange: "$$",
    foundingDate: "",
    areaServed: ["NJ 07114"],
    openingHours: []
  },

  // === ANALYTICS ===
  analytics: {
    ga4Id: "",
    metaPixelId: "",
    hotjarId: "",
    clarityId: ""
  },

  // === COOKIE CONSENT ===
  cookieConsent: {
    text: "We use cookies to improve your experience and analyze site traffic.",
    acceptButton: "Accept",
    declineButton: "No Thanks",
    privacyUrl: "#"
  },

  // === CHATBOT (disabled — toggle off in builder) ===
  chatbot: { enabled: false },

  // === BRAND VOICE ===
  // Shapes AI-composed copy AND folds into the chatbot system prompt.
  brand: {
    targetCustomer: "",
    differentiators: [],
    voiceNotes: ""
  },

  // === OPS / NOTIFICATIONS (all tiers) ===
  // Lead routing + report recipient. Consumed by /api/site-lead.js
  // and the monthly reporting cron.
  ops: {
    leadEmail: "",
    leadCcEmail: "",
    leadAlertCadence: "instant",
    reportEmail: "",
    ownerNotes: ""
  },

  // === LEGAL (drives generated /privacy, /terms, /accessibility) ===
  legal: {
    name: "Haddad Plumbing & Heating Inc",
    privacyEmail: "",
    jurisdiction: "",
    effectiveDate: "2026-06-06"
  }
};
